repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/Takishima/cmake-pre-commit-hooks
    rev: v1.9.6
    hooks:
      - id: clang-format
        args:
          - '-Bcmake-build-pre-commit'
          - '-i'
        additional_dependencies:
          - clang-format
      - id: clang-tidy
        args:
          - '-Bcmake-build-pre-commit'
        additional_dependencies:
          - clang-tidy
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.1
    hooks:
      - id: check-github-workflows
